### ISSUE TITLE
Could I get I UIImage

### ISSUE THREAD

**Issue by CoderDream** [SDWebImage/SDWebImageWebPCoder#20]
I need to init an UIImage via webp, then I can cut the webp.
How can I use SDWebImageWebPCoder to implement it? Thanks a lot.
============
let image = UIImage() // getImage
let rect = CGRect(x: 50, y: 50, width: 50, height: 50)
let cgImageCorpped = image.cgImage?.cropping(to: rect)
let imageCorpped = UIImage(cgImage: cgImageCorpped!)

**Comment by kinarobin** [comment]
See if this can help you ？

```ruby
- (nullable UIImage *)decodedImageWithData:(nullable NSData *)data
                                   options:(nullable SDImageCoderOptions *)options;
```

**Comment by kinarobin** [comment]
Since `SDWebImageWebPCoder` conform `<SDProgressiveImageCoder, SDAnimatedImageCoder>` protocol.

You can see detail  in `SDImageCoder`:

[https://github.com/SDWebImage/SDWebImage/blob/841662d36a34561390ad8d9d8bb02313b0b7da20/SDWebImage/SDImageCoder.h#L56](https://github.com/SDWebImage/SDWebImage/blob/841662d36a34561390ad8d9d8bb02313b0b7da20/SDWebImage/SDImageCoder.h#L56)

**Comment by dreampiggy** [comment]
UIImage is bitmap image, it does not contains any where original compressed format (PNG/JPEG/WEBP) is.

Just do your image process logic like **CUT**, then if you want to output a WebP format, do a image encoding again.

```objective-c
UIImage *image;
UIImage *croppedImage = [image sd_croppedImageWithRect:rect];
NSData *croppedImageData = [croppedImage sd_imageDataAsFormat:SDImageFormatWebP];
```
