### ISSUE TITLE
High memory usage in RNFI

### ISSUE THREAD

**Issue by jochem725** [SDWebImage/SDWebImageWebPCoder#29]
Hi,

I'm using `SDWebImageWebPCoder` with `react-native-fast-image` and I found that the memory usage is quite high. We use non-animated WebP images but it seems like RNFI uses SDAnimatedImageView to load the images. After profiling I found both  `_canvas` and `imageRef` in `safeAnimatedImageFrameAtIndex` are retained. Which makes sense I guess since the canvas is reused for the animation. However for images this causes unnecessary memory usage.

As a temporary workaround I altered `animatedImageFrameAtIndex` so it releases the canvas after the final frame of the animation (which for an image is immediately)

```objective-c
- (UIImage *)animatedImageFrameAtIndex:(NSUInteger)index {
    UIImage *image;
    if (index >= _frameCount) {
        return nil;
    }
    SD_LOCK(_lock);
    image = [self safeAnimatedImageFrameAtIndex:index];
    SD_UNLOCK(_lock);
    
    if (index + 1 >= _frameCount) {
        CGContextRelease(_canvas);
        _canvas = NULL;
    }

    return image;
}
```

I don't think this is a great workaround since it impacts the behavior for animated WebP images (but it may be unnecessary to keep two copies of the image in memory?) so I wondered if there is another way to reduce the memory usage of WebP in SDWebImage and possibly improve RNFI.

**Comment by dreampiggy** [comment]
You can not do this. Because `each frame does not guranteed to kept in the RAM`. You assume `after each frame was decoded, they're all cached.` this is wrong.

Check our wiki for detail about the [Animated Image Rerndering solution](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#animated-image-50), you'll know how and why we design the animated image like this.

**Comment by dreampiggy** [comment]
There are one control behavior, the `SDAnimatedImage.preloadAllFrames`, this will actually load each frame into RAM, and does not decode them any more.

But, since this preload can be reverted using `unloadAllFrames`, a better solution is that for non-animated image, we does not use the `SDAnimatedImage` instance at all.

The init method in `SDAnimatedImage` should just check the frame count. If the frame count is 1, then we return nil, this can solve the problem.

**Comment by jochem725** [comment]
@dreampiggy Great, thank you for your quick response. I expected something like that was happening. I agree that a better solution would be to not use `SDAnimatedImage` in these cases.

**Comment by dreampiggy** [comment]
@jochem725 I release a quick fix via [SDWebImageWebPCoder v0.3.1](https://github.com/SDWebImage/SDWebImageWebPCoder/releases/tag/0.3.1). Please update and have a check again for this.

**Comment by jochem725** [comment]
@dreampiggy v0.3.1 solves the issue, again thanks for the quick fix 😄

**Comment by dreampiggy** [comment]
@jochem725 [SDWebImage 5.4.2](https://github.com/SDWebImage/SDWebImage/releases/tag/5.4.2) released as well. This WebPCoder can only fix for WebP, but not other thing like APNG/HEIF/AVIF format. It's better to upgrade to 5.4.2 version as well, which fix the issue from scratch.

**Comment by jochem725** [comment]
@dreampiggy I updated to SDWebImage 5.4.2, it works great.
Again, thanks for your quick response :)

**Comment by Stafox** [comment]
hey @dreampiggy . Looks like the issue still exists for ios < 14.0
Can reproduce on devices with ios 12 and ios 13. On ios14 works fine because in 5.9.0 started used native coder implementation.

Any idea how to fix it?

**Comment by dreampiggy** [comment]
Provide your instrument profile result. And usage.

High memory usage != memory leak. There are different things.

And, for WebP images, the decoding algorithm of standard WebP need a canvas to draw animated images. For static image it does not need. So it may be some different cases between these animation/static.

**Comment by dreampiggy** [comment]
And, make sure you must use SDWebImageWebPCoder >= 0.6.1. (Pay attention if you use `react-native-fast-image`, you should not use the ebmed vendered framework via JavaScript npm package. Use CocoaPods to manage the iOS native dependency)

The old version before 0.5.0 use the canvas even for static images, which is useless.

**Comment by Stafox** [comment]
@dreampiggy thanks for a quick response. Have checked. In pod manifest SDWebImageWebPCoder = 0.6.1.
```
 - SDWebImage (5.9.4):
    - SDWebImage/Core (= 5.9.4)
  - SDWebImage/Core (5.9.4)
  - SDWebImageWebPCoder (0.6.1):
    - libwebp (~> 1.0)
    - SDWebImage/Core (~> 5.7)
```

Have tried also without fast image, but with another lib which used SDWebImageWebPCoder as dependency. Result is the same.

![image](https://user-images.githubusercontent.com/1101646/97115202-809dcd00-1706-11eb-8fab-18c4e380aff0.png)

On that image showed memory usage when 12 images were rendered. Size of each image about 60-80 kb.

**Comment by Stafox** [comment]
About code usage.

I render images using [ImageBackground](https://reactnative.dev/docs/imagebackground) (which uses Image component. Native code is [here](https://github.com/facebook/react-native/tree/0.63-stable/Libraries/Image)) component.

Also to add support of webp I've used [react-native-webp-format](https://github.com/Aleksefo/react-native-webp-format) (native code is [here](https://github.com/Aleksefo/react-native-webp-format/blob/master/ios/WebPImageDataDecoder.m)).

Also a little bit more info about images:
I've generated them using imagick with the following options.

```
            $image->getImagick()->setOption('webp:low-memory', 'true');
            $image->getImagick()->setOption('webp:method', '6');
            $image->getImagick()->setImageFormat('WEBP');
            $image->getImagick()->unsharpMaskImage(0.25, 0.25, 8, 0.065);
            $image->getImagick()->setInterlaceScheme(\Imagick::INTERLACE_NO);
            $image->getImagick()->setColorspace(\Imagick::COLORSPACE_SRGB);
            $image->getImagick()->setCompression(\Imagick::COMPRESSION_LZMA);
            $image->getImagick()->setImageCompressionQuality(80);
```

Also attach image sample (put it into zip because github does not allow to attach webp). 
[thumb_dcee16ff-ac19-4452-8784-605ff9e39848_photos_medium.webp.zip](https://github.com/SDWebImage/SDWebImageWebPCoder/files/5437628/thumb_dcee16ff-ac19-4452-8784-605ff9e39848_photos_medium.webp.zip)

**Comment by Stafox** [comment]
@dreampiggy let me know if more details needed.

**Comment by dreampiggy** [comment]
Maybe enough. I'll have a check in 1 day. Thanks for your reply.

**Comment by baronha** [comment]
> Maybe enough. I'll have a check in 1 day. Thanks for your reply.

Do you solve it?
