### ISSUE TITLE
XCode 12.0 problem

### ISSUE THREAD

**Issue by milika** [SDWebImage/SDWebImageWebPCoder#44]
When building a project with SDWebImageWebPCoder i get multiple
The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.

Did not happen on XCode 11, i suppose its because ios8 emulators are depreciated

Thanks

**Comment by BryanNorden** [comment]
Can confirm this is happening to me too. Please fix this

**Comment by dreampiggy** [comment]
This is because of libwebp. They need another version release, so that I can update the `SwiftPM/CocoaPods/Carthage` configuration.

See more: https://github.com/SDWebImage/libwebp-Xcode/pull/5

If they don't release any version, I can not release a version by myself without breaking the concept (libwebp's version should match Google's version).

**Comment by dreampiggy** [comment]
Maybe the better idea is to ask Google's guys to release new libwebp's version:

https://groups.google.com/a/webmproject.org/d/forum/webp-discuss

**Comment by mmdumi** [comment]
@dreampiggy It looks like nobody is merging the above PR as it's been some time now. 
In the meantime Carthage is ready to compile xcframeworks and I'm trying to make my project compile for M1 Macs. Currently  SDWebImageWebPCoder is the only dependency that blocks me from running the project.
Is there something I can do on my end to compile the xcframework version of SDWebImageWebPCoder ?

**Comment by dreampiggy** [comment]
Solved by both SDWebImage/libwebp-Xcode#5 and SDWebImage/SDWebImageWebPCoder#48
