### ISSUE TITLE
Encounter an occasional `NSRangeException` crash

### ISSUE THREAD

**Issue by xuzhongping** [SDWebImage/SDWebImageWebPCoder#67]
Hi, I have an occasional out-of-bounds crash, but I can't give the necessary steps, the scene that comes up has tons of webp animations playing, and I can provide the stack:
```
#0 Thread

NSRangeException

*** -[__NSFrozenArrayM objectAtIndexedSubscript:]: index 66 beyond bounds for empty array

CoreFoundation
___exceptionPreprocess + 216
3
CoreFoundation
-[__NSFrozenArrayM objectAtIndexedSubscript:] + 120
4
MyAPP
-[SDImageWebPCoder animatedImageDurationAtIndex:] (SDImageWebPCoder.m:0)
5
MyAPP
-[SDAnimatedImage animatedImageDurationAtIndex:] (SDAnimatedImage.m:0)
6
MyAPP
-[SDAnimatedImagePlayer displayDidRefresh:] (SDAnimatedImagePlayer.m:296)
7
MyAPP
-[SDDisplayLink displayLinkDidRefresh:] (SDDisplayLink.m:205)
```
In addition, I see this code, is there a potential thread insecurity here?
```
- (NSTimeInterval)animatedImageDurationAtIndex:(NSUInteger)index {
    if (index >= _frameCount) {
        return 0;
    }
    if (_frameCount <= 1) {
        return 0;
    }
    return _frames[index].duration;
}
```

**Comment by dreampiggy** [comment]
Maybe. But for most cases, the static animated coder could not change the image data and frame count. So the `_frameCount` and `_frames`, is actually readonly because it only initialize once in the objc init method. (Check code there)

Only those incremental decoding, which may update the `_frameCount` variable, has potential thread-safe issue and need to be guarded by lock or some atomic logic.

**Comment by dreampiggy** [comment]
@xuzhongping I believe this PR can fix the issue. Which does not effect the normal animation decoding speed.

I'll release a new patch version for SDWebImageWebPCoder, please have a try.
