### ISSUE TITLE
(nullable NSData *)sd_encodedWebpDataWithImage returns NIL after 0.14.2 update

### ISSUE THREAD

**Issue by DanielZanchi** [SDWebImage/SDWebImageWebPCoder#94]
After updating the framework to 0.14.2 if I try to get the data of a clear (transparent) UIImage it will return NIL.

`- (nullable NSData *)sd_encodedWebpDataWithImage 
`
enters line 904 and returns NIL:
```
    if (error != kvImageNoError) {
        return nil;
    }
```

**Comment by dreampiggy** [comment]
> clear (transparent) UIImage 

Can you provide a reproduce demo ? Or code to trigger this.

> After updating the framework to 0.14.2

From which version to 0.14.2 ? Is there any iOS version bump or min-deployment-target bump during the version upgrade?

I can't find anything related to WebP Encoding during the recent version bump.

**Comment by DanielZanchi** [comment]
I don't have that problem with version 0.14.1. 
after 0.14.2 i got that problem

**Comment by DanielZanchi** [comment]
to reproduce:
extension to create an image from a color:
`extension UIColor {
    
	public func image(ofSize size: CGSize, scale: CGFloat = 1) -> UIImage {
		let format = UIGraphicsImageRendererFormat.default()
		format.scale = scale
        return UIGraphicsImageRenderer(size: size, format: format).image { rendererContext in
            self.setFill()
            rendererContext.fill(CGRect(origin: .zero, size: size))
        }
    }
    
}
`

create the image and get the WebP data:
```
let clearImage = UIColor.clear.image(ofSize: CGSize(width: 512, height: 512), scale: 1)
let data = SDImageWebPCoder.shared.encodedData(with: clearImage, format: .webP, options: [.encodeMaxFileSize: WhatsappLimits.maxStaticStickerFileSize - 10])
```

**_data_** will be **nil**

**Comment by dreampiggy** [comment]
https://github.com/SDWebImage/SDWebImageWebPCoder/compare/0.14.1...0.14.2

Is this cause the issue ?

![image](https://github.com/SDWebImage/SDWebImageWebPCoder/assets/6919743/b8daeb9d-65fb-441a-88a6-747375321dad)

But I don't think this vImage changes is wrong. Because the `vImageBuffer_initWithCGImage` should handle this case

Or this is Apple's vImage bug...They should match the documentation behavior:

See: https://developer.apple.com/documentation/accelerate/1399118-vimagebuffer_initwithcgimage

**Comment by dreampiggy** [comment]
If this still cause issue, I can just revert this changes and re-release v0.14.3

**Comment by dreampiggy** [comment]
Your example code,  seems want to encode 8-bit WebP (using RGBA8888) into the wide color (extended color) (RGBA16161616), this cause issue

**Comment by dreampiggy** [comment]
Seems suck on vImage's API

If the input color use 16bit HDR CGImage
We want to encode the 8bit non-HDR WebP data

This need special code to handle this, or vImage will report error :(

**Comment by dreampiggy** [comment]
But I can not revert to previous one, since that's color space is used to solve https://github.com/SDWebImage/SDWebImageWebPCoder/pull/90

A better solid fix, is:

1. We only supports some number of color spaces (because of libwebp encoding the vImage convert color space)
2. If your input image does not provide the color space we support, we will convert always into sRGBA (for example, a white color or black color CGImage only, which use monochrome colorspace)

**Comment by dreampiggy** [comment]
Fixed, but I also found SDWebImage's `SDImageCoderHelper CGImageCreateScaled` contains the same issue.

We don't really happy with the Monochrome CGImage, you can always use `[UIColor colorWithRed:0 green:0 blue:0 alpha:1]` instead of clear color

Our encoding API in history, only prefers the rgba color, not white-alpha color, because this is the most common use case and we're not professional Image Editing library :)

**Comment by dreampiggy** [comment]
@DanielZanchi Try using the #95 and test again

My test case can succefully encode this monochrome clear color

**Comment by DanielZanchi** [comment]
> @DanielZanchi Try using the #95 and test again
> 
> My test case can succefully encode this monochrome clear color

That works! Thanks
